version: '3'
services:
  canary-view-api:
    build: canary-view-api/
    networks:
      - canary-network
    ports:
      - 8082:8082
  canary-api:
    build: canary-api/
    networks:
      - canary-network
    ports:
      - 8081:8081
  canary-event-consumer:
    build: canary-event-consumer/
    networks:
      - canary-network
    environment:
      DATABASE_URL: postgresql://canary-user:canary-pass@postgre:5432/CanaryDB?schema=public
      KAFKA_BOOTSTRAP_SEVER: kafka:29092
networks:
  canary-network:
    external:
      name: canary-network
