version: '3'
services:
  canary-view-api:
    build: canary-view-api/
    networks:
      - canary-network
    ports:
      - 8082:8082
  canary-api:
    build: canary-api/
    networks:
      - canary-network
    ports:
      - 8081:8081
networks:
  canary-network:
    external:
      name: canary-network