steps:
  - name: 'gradle:7.3.2-jdk11'
    dir: 'canary-api'
    entrypoint: 'gradle'
    args: [ 'test' ]

  - name: 'gradle:7.3.2-jdk11'
    dir: 'canary-api'
    entrypoint: 'gradle'
    args: [ 'bootJar' ]

  - name: 'docker:20.10.12'
    dir: 'canary-api'
    args: [ 'build',
            '--tag', 'gcr.io/$PROJECT_ID/canary-api:latest',
            '--tag', 'gcr.io/$PROJECT_ID/canary-api:$SHORT_SHA',
            '.' ]

  - name: 'docker:20.10.12'
    dir: 'canary-api'
    args: [ 'image', 'push', 'gcr.io/$PROJECT_ID/canary-api', '--all-tags' ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:370.0.0'
    dir: 'canary-api'
    args: [ 'gcloud', 'run', 'deploy', 'canary-api',
            '--image', 'gcr.io/$PROJECT_ID/canary-api:$SHORT_SHA',
            '--region', 'southamerica-west1',
            '--allow-unauthenticated']
