name: "Build & Publish Canary Api image"
on:
  push:
    branches: [main]
    paths:
      - "canary-api"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "canary-api"
  CWD: "canary-api"

jobs:
  build:
    name: Build & Publish docker image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.CWD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: ${{ env.CWD }}
          arguments: bootJar

      - name: Generate Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Retrieve Docker Metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}
          tags: type=semver,pattern={{version}},value=${{ steps.tag_version.outputs.new_tag }}

      - name: Authenticate to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.CWD }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
